### ISSUE TITLE
Start failed

### ISSUE THREAD

**Issue by jbwl** [kak-tus/ruthie#1]
Running ruthie from docker as per the README, this error appears:

`Start failed: dial tcp 127.0.0.1:6379: connect: connection refused`

While 

`telnet 127.0.0.1 6379`

connects with no problems.

This is on macos 10.14, redis 5.0.5

**Comment by kak-tus** [comment]
This is because, that Ruthie works only with Redis Cluster.
See https://redis.io/topics/cluster-tutorial

Redis running in cluster mode usually use 7000 port. You can run cluster with docker on single node and different ports.

**Comment by jbwl** [comment]
Oh OK, thanks for the clarification.
